Repository aragon/nest, pull requests merged in 2018-06, with the labels that each got.

#36 Prysmatic Labs Request for Funding (Sharding)
  grants/PrysmaticLabs/roadmap.md
  grants/PrysmaticLabs/team.md
Labels: application: granted, ecosystem: ethereum

#25 Frame: OS-level Signing Provider
  grants/Frame/roadmap.md
  grants/Frame/team.md
Labels: application: granted, ecosystem: aragon, ecosystem: broader crypto

#30 Gnarly Nest Proposal
  grants/gnarly/roadmap.md
  grants/gnarly/team.md
Labels: application: granted, ecosystem: aragon, ecosystem: ethereum

#31 wespr / pando
  grants/wespr_pando/roadmap.md
  grants/wespr_pando/team.md
Labels: application: granted, ecosystem: aragon, ecosystem: ethereum

#45 Scalable voting request for funding
  grants/scalable_voting/roadmap.md
  grants/scalable_voting/team.md
Labels: application: granted, ecosystem: aragon, ecosystem: ethereum
